# golang image where workspace (GOPATH) configured at /go.
FROM golang:1.12

# Command line argument
#ARG REPO=gitlab.com/mst-services/mst-microservice-sample-go
ARG REPO

# Setting up working directory
WORKDIR /go/src/${REPO}

# Copy project dependencies
ENV GO111MODULE=on
ADD ./go.* ./

# Restore dependencies
RUN go mod vendor

# Copy the local package files to the container's workspace
ADD . .

# Build the main binary
RUN go build -o /go/bin/run .



