name: Pip.Services Commons toolkit in Go

on:
  push:
    paths:
      - "**"
      - "!README.md"

jobs:
  Default:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@main

      ############# Prepare #############

      - name: Install prereq and save build number
        id: build_info
        uses: pip-devops/actions/go/prepare@v1

      ############# Build and test #############

      # - name: Build the component
      #   uses: pip-devops/actions/go/build@v1

      - name: Test the component
        uses: pip-devops/actions/go/test@v1

      ############# Release #############

      - name: Tag branch with the build number
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.build_info.outputs.component_version }}-${{ steps.build_info.outputs.build_number }}"

      ############# Clear #############

      - name: Clean up
        uses: pip-devops/actions/node/clear@v1
